# copy of /.cargo/config.toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "/home/will/Desktop/2022/Cursos/Rust/rust_os/x86_64-blog_os.json"